### PR TITLE
ws json improvements

### PR DESCRIPTION
**Pull request by benjgil**
## Proposed Changes

- move default env in ws.json to be inside the env aspect config
- add org placeholder to default scope
-

### CODE REVIEW

**Comment by GiladShoham** [comment]
@benjgil This will cause errors when uncomment it.
I don't think this is the right approach. 
Can I close it?

**Comment by benjgil** [comment]
@GiladShoham then please suggest something we can put here instead. We definitely shouldnt be leaving the current ws.json template which is a practice we recommend against and will also cause the same error.

How about just have a commented example:
// Add a variant like so. In this example we are adding a variant for any components inside the "components" directory in the workspace
// "components": {
//  "teambit.react/react: {} // this line applies the base bit react environment to components in this rule
// }

Have edited the PR with the above, please comment again

**Comment by GiladShoham** [comment]
@benjgil that's better.
I would move the `https://harmony-docs.bit.dev/aspects/variants` to be above the `teambit.workspace/variants`
Let's discuss this change with @itaymendel

**Comment by benjgil** [comment]
Great.
@itaymendel what do you think?

**Pull request closed without merging**
