### PR TITLE
"quite" typo

### PR DESCRIPTION
**Pull request by benjgil**
## Proposed Changes

- changed quite to quiet. Could cause issues in future when trying to implement aspect APIs
-
-

### CODE REVIEW

**Comment by davidfirst** [comment]
@benjgil , what's the status of this PR? please let me know if you need help with it. (seems like the base branch is incorrect)

**Comment by benjgil** [comment]
@davidfirst - I'm not sure. I posted the PR a while ago and apparently it got ignored!

Not sure what you meant by the base branch being incorrect - it's possible this typo's been corrected already on master. But it's a potentially important typo if it's still in the code, as the 'quiet' functionality could get lost if it's named 'quite'

**Comment by benjgil** [comment]
Hmm, now I can see what you mean. Not sure why merging back from master didnt sync the two branches.

This PR can be closed, but worth checking to see if the 'quite' typo still exists in the code (could be in multiple places) and clear it up. I dont work with bit code much at the moment so my environment isnt up to date

**Comment by davidfirst** [comment]
@benjgil , I created a new PR for this, please approve it.
https://github.com/teambit/bit/pull/3427

I'm closing this one.

**Pull request closed without merging**
