### PR TITLE
fix error "Cannot find type definition file for fs-capacitor" during bit-build

### PR DESCRIPTION
**Pull request by davidfirst**

### CODE REVIEW

**Comment by zkochan** [comment]
No changes to the lockfile?

**Comment by davidfirst** [comment]
> No changes to the lockfile?

Lots of changes, but I never commit them, I let the CI handle it. Is it better to have it as part of the commit?

**Review by zkochan — APPROVED** [review]

**Comment by zkochan** [comment]
It is better because when the lockfile is up-to-date then installation is faster. Also, you see what changes to the deps happened.

**Comment by davidfirst** [comment]
> It is better because when the lockfile is up-to-date then installation is faster. Also, you see what changes to the deps happened.

oh ok, makes sense. I added the file.

**Comment by davidfirst** [comment]
@zkochan , I removed the file :) 
Turns out that when I generate the file locally, it's written with the new registry, but circleCI works with the old registry. that's why setup-harmony failed.

**Pull request merged**
