### PR TITLE
fix: cli links

### PR DESCRIPTION
**Pull request by debs-obrien**
## Proposed Changes

adds links to new docs for cli messages

### CODE REVIEW

**Comment by debs-obrien** [comment]
This needs a discussion with @itaymendel over which links should remain for legacy and which should be have both and which only harmony.

**Comment by itaymendel** [comment]
honestly i think that to do a proper job here we need complete CLI-reference in new docs autogenerated from Bit.
@GiladShoham

**Comment by GiladShoham** [comment]
@debs-obrien needs to be re-done

**Comment by GiladShoham** [comment]
@debs-obrien All the links are going to change in the next few days, so closing it.

**Pull request closed without merging**
