### PR TITLE
prettify support for all file types (especially (s)css)

### PR DESCRIPTION
**Pull request by KutnerUri**
## Proposed Changes

- auto-deduce parser for prettier (we can add overrides later on if we run into parse errors) 
- add `scss` to auto prettier list
- did not prettify existing files (I don't want to get conflicts)

### CODE REVIEW

**Comment by KutnerUri** [comment]
PS. script `prettier:check` seems broken, it's 
```
prettier --list-different "{ts,js,css,tsx}/**/*.{ts,js,css,tsx}"
```
shouldn't it be 
```
prettier --list-different \"{src,e2e}/**/*.{ts,js,css,tsx}\"
```

**Comment by davidfirst** [comment]
@KutnerUri , looks good.
Regarding `prettier --list-different`, you're right. It's currently incorrect. (probably no one ever used it).

**Comment by KutnerUri** [comment]
Gilad wanted me to prettify existing css files before merging. I will make sure with Ran and Oded, prettify and merge

**Comment by KutnerUri** [comment]
* merge from master
* prettified all existing css
* regenerated package lock

@GiladShoham - ok to merge (hoping tests will pas)

**Pull request merged**
