### PR TITLE
fix "bit init --reset-hard" to remove the legacy "bit" prop in package.json and to re-create the workspace.jsonc file

### PR DESCRIPTION
**Pull request by davidfirst**
Reported by @benjgil .

### CODE REVIEW

**Comment by benjgil** [comment]
@davidfirst 
So just to make sure - is the `--reset-hard` flag now going to just totally remove bit from the current project, or will it try to re-initialise bit too?
IMO - it should just remove anything bit, and then the user can choose to reinitialise if they want to

**Review by GiladShoham — APPROVED** [review]

**Comment by davidfirst** [comment]
@benjgil , it re-init bit as well. This is how this flag was always working. We can create a new flag to remove Bit completely if needed.

**Comment by benjgil** [comment]
@davidfirst 
I think a flag removing bit entirely would be a useful addition.
So the current --reset-hard will remove bit, and then run the default `bit init`, meaning that now it will always initialise a Harmony workspace?

**Comment by davidfirst** [comment]
@benjgil , yes that's correct. (as long as they use a Harmony version and not v14.8.8).

**Pull request merged**
