### PR TITLE
New extension template [ci skip]

### PR DESCRIPTION
**Pull request by GiladShoham**
## Proposed Changes

- A template for new extension README.md file
- A template for new extension file structure

**All the intro part shouldn't be part of the final readme. it's just temp readme of the readme**

---
This change is [Reviewable](https://reviewable.io/reviews/teambit/bit/2611)

### CODE REVIEW

**Comment by davidfirst** [comment]
1. Do we want to add `template.cmd.tsx` file? probably most of the extensions won't create new commands and won't need it.

2. hooks.
Not sure they could always be exposed from the index.ts, I see how some hooks are needed inside the extensions itself - `template.extension.ts`. In some cases, you need the class' state. 

3. "types.ts" file.
I don't think it's really needed. Examples for types of the workspace/component config should be added to the README because that's where the user gets the data on how to use the extension. It won't be convenient to let the user go back and forth from the readme to the types.

**Comment by GiladShoham** [comment]
@davidfirst 
Thanks!
1. We can always delete it. (we can instruction about the fact you can remove it). I think it's better there incase you will add one to make sure its consistence. I don't think someone will miss removing it in case he doesn't need it.
2. Agree, that's dependents mainly on the final design of harmony. in case it won't be possible we will expose it from the template.extension.ts
3. types.ts is not about an example of the types. it's about the types themselves to use in the code. examples of objects that use these types, will be in the readme.
I don't want to copy the type itself, since then we will have 2 sources of truth for this. and the readme will probably get out of sync sometimes.
Also, we can always add a link from the readme into the types.

**Comment by qballer** [comment]
https://github.com/teambit/bit/blob/harmony/main/src/extensions/flows/README.md

Both Itay and I worked on this readme, which we can derive a simpler template.
On top of that we should have an RFC process within bit when a PR changes/suggests API's

**Comment by GiladShoham** [comment]
@qballer This one is much simpler than what you have in the flows.
All the intro part shouldn't be part of the final readme. it's just temp readme of the readme.

**Comment by davidfirst** [comment]
OK. LGTM.

**Pull request closed without merging**
