### PR TITLE
feat: backup .bitmap file before writing to it

### PR DESCRIPTION
**Pull request by davidfirst**
Back it up to the local scope inside `bitmap-history` dir.

### CODE REVIEW

**Comment by GiladShoham** [comment]
@davidfirst 
Make sure to call it with `.` at the beginning. like .bitmap-history

**Comment by davidfirst** [comment]
> @davidfirst Make sure to call it with `.` at the beginning. like .bitmap-history

why?

**Comment by GiladShoham** [comment]
to make it hidden and not tracked by git

**Comment by davidfirst** [comment]
but it's inside `.bit` (or `.git/bit`) so the dir is never tracked regardless

**Comment by GiladShoham** [comment]
ohhh ok, I missed it, in that case, it's fine

**Review by GiladShoham — APPROVED** [review]

**Pull request merged**
